services:
  wallos:
    container_name: wallos
    image: tissak/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'America/Los_Angeles'
    # Volumes store your data between container upgrades
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
